In [44]:
import numpy as np


In [45]:
data=np.random.randint(0,8,(4,4))
data


array([[0, 3, 4, 5],
       [0, 6, 2, 7],
       [7, 0, 3, 6],
       [7, 6, 0, 6]])

In [46]:
data.sum()


np.int64(62)

In [47]:
data.sum(axis=1)


array([12, 15, 16, 19])

In [48]:
data.sum(axis=0)


array([14, 15,  9, 24])

In [49]:
data.max()


np.int64(7)

In [50]:
data.max(axis=1)

array([5, 7, 7, 7])

In [51]:
data.argmax(axis=1)


array([3, 3, 0, 0])

In [52]:
data.sum(axis=1).argmin()+1


np.int64(1)

In [53]:
data.sum(axis=1)


array([12, 15, 16, 19])

In [54]:
data.sum(axis=0)


array([14, 15,  9, 24])

In [55]:
data.sum()


np.int64(62)

In [56]:
data=np.random.randint(10,100,(10,5))


In [57]:
data.sum(axis=0).argmax()+1


np.int64(4)

In [58]:
data.sum(axis=0)


array([528, 337, 437, 751, 565])

In [59]:
data.sum(axis=0)[3:].sum()


np.int64(1316)

In [60]:
data[:,2:5].sum()


np.int64(1753)

In [61]:
data.sum(axis=0).max()


np.int64(751)

In [62]:
data.sum(axis=0).min()


np.int64(337)

In [63]:
data.sum(axis=0).max()-data.sum(axis=0).min()


np.int64(414)

In [64]:
data=np.random.randint(0,8,8)


In [65]:
data.mean()


np.float64(4.625)

In [66]:
np.median(data)


np.float64(6.0)

In [67]:
data

array([7, 7, 7, 7, 5, 0, 3, 1])

In [68]:
np.quantile(data,0.24)


np.float64(2.36)

In [69]:
np.quantile(data,0.45)


np.float64(5.3)

In [70]:
np.quantile(data,0.43)


np.float64(5.02)

In [71]:
np.median(data)


np.float64(6.0)

In [72]:
np.std(data)


np.float64(2.7357585785299112)

In [73]:
np.var(data)


np.float64(7.484375)

In [74]:
data=np.random.randint(0,6,(6,2))


In [75]:
np.corrcoef(data.T)


array([[1.        , 0.69989647],
       [0.69989647, 1.        ]])

In [76]:
v1=np.arange(2,16)
v1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
v2=np.arange(50,60)
v2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [78]:
x=[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
x.reverse()
v2=np.array(x)
v2


array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

In [79]:
data=v1
data=v2


In [80]:
np.corrcoef(data.T)


np.float64(1.0)

In [81]:
data=np.random.randint(0,15,(6,6))


In [82]:
np.corrcoef(data)


array([[ 1.        ,  0.08655522,  0.57103454,  0.11370053,  0.14296972,
         0.03825771],
       [ 0.08655522,  1.        , -0.04293573, -0.4360027 , -0.76592358,
         0.33224427],
       [ 0.57103454, -0.04293573,  1.        ,  0.55632065,  0.0225655 ,
         0.55984353],
       [ 0.11370053, -0.4360027 ,  0.55632065,  1.        , -0.0943549 ,
         0.61782079],
       [ 0.14296972, -0.76592358,  0.0225655 , -0.0943549 ,  1.        ,
        -0.7340993 ],
       [ 0.03825771,  0.33224427,  0.55984353,  0.61782079, -0.7340993 ,
         1.        ]])