In [1]:

import numpy as np

In [2]:
data=np.random.randint(0,20,5)

In [3]:
data

array([ 5, 18, 10, 16,  5])

In [4]:
data+3

array([ 8, 21, 13, 19,  8])

In [5]:
x=np.random.randint(0,10,(4,5))
x

array([[9, 6, 0, 3, 1],
       [2, 3, 0, 1, 3],
       [2, 0, 8, 1, 6],
       [3, 8, 4, 3, 0]])

In [6]:
y=np.random.randint(0,10,(1,5))
y

array([[8, 5, 2, 4, 3]])

In [7]:
[7, 1, 3]
[7, 1, 3]
[7, 1, 3]
[7, 1, 3]

[7, 1, 3]

In [8]:
y

array([[8, 5, 2, 4, 3]])

In [9]:
x+y

array([[17, 11,  2,  7,  4],
       [10,  8,  2,  5,  6],
       [10,  5, 10,  5,  9],
       [11, 13,  6,  7,  3]])

In [10]:
x=np.random.randint(0,10,(4,1))

In [11]:
x

array([[4],
       [8],
       [7],
       [3]])

In [12]:
y

array([[8, 5, 2, 4, 3]])

In [13]:
[3, 3, 9, 9]
[3, 3, 9, 9]
[3, 3, 9, 9]
[3, 3, 9, 9]

[3, 3, 9, 9]

In [14]:
5555
1111
1111
5555

5555

In [15]:
x+y

array([[12,  9,  6,  8,  7],
       [16, 13, 10, 12, 11],
       [15, 12,  9, 11, 10],
       [11,  8,  5,  7,  6]])

In [16]:
x

array([[4],
       [8],
       [7],
       [3]])

In [17]:
y

array([[8, 5, 2, 4, 3]])

In [18]:
data=np.random.randint(0,20,5)

In [19]:
data.shape

(5,)

In [20]:
data

array([14, 18,  1,  8,  9])

In [21]:
data.cumsum()

array([14, 32, 33, 41, 50])

In [22]:
data.cumprod()

array([   14,   252,   252,  2016, 18144])

In [23]:
data=np.random.randint(0,20,(4,4))

In [24]:
data

array([[ 3, 15, 18, 17],
       [19, 17, 12,  1],
       [11,  4,  5,  3],
       [12, 12, 12,  4]])

In [25]:
data.cumsum(axis=1)

array([[ 3, 18, 36, 53],
       [19, 36, 48, 49],
       [11, 15, 20, 23],
       [12, 24, 36, 40]])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [28]:
a=np.random.choice([20,30,40,50,60],size=3)
a

array([50, 60, 50])

In [29]:
a=np.random.choice([20,30,40,50,60],size=3,replace=True)

In [30]:
a

array([20, 30, 20])

In [31]:
a=np.random.choice([20,30,40,50,60],size=3,replace=False)

In [32]:
a

array([40, 50, 60])