In [ ]:
import numpy as np

retail_np_array=np.array([
    [1001, "laptop", 1, 50000, 50000],
    [1002, "mouse",2, 500, 1000],
    [1003, "keybord", 1, 1000, 1000],
    [1004, "monitor", 2, 7000, 14000],
    [1005, "Headphones", 1, 2000, 2000]

], dtype=object)
retail_np_array


# # Existing columns
# customer_id = retail_np_array[:, 0]
# product = retail_np_array[:, 1]
# quantities = retail_np_array[:, 2].astype(int)
# price = retail_np_array[:, 3].astype(int)
# total = retail_np_array[:, 4].astype(int)

array([[1001, 'laptop', 1, 50000, 50000],
       [1002, 'mouse', 2, 500, 1000],
       [1003, 'keybord', 1, 1000, 1000],
       [1004, 'monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
customer_id = retail_np_array[:, 0]
customer_id

array([1001, 1002, 1003, 1004, 1005], dtype=object)

In [ ]:
product = retail_np_array[:, 1]
product

array(['laptop', 'mouse', 'keybord', 'monitor', 'Headphones'],
      dtype=object)

In [ ]:
quantities = retail_np_array[:, 2].astype(int)
quantities

array([1, 2, 1, 2, 1])

In [ ]:
price = retail_np_array[:, 3].astype(int)
price

array([50000,   500,  1000,  7000,  2000])

In [ ]:
total = retail_np_array[:, 4].astype(int)
total

array([50000,  1000,  1000, 14000,  2000])

In [ ]:
retail_np_array.shape[0],

(5,)

In [ ]:
np.sum(total),

(np.int64(68000),)

In [ ]:
np.mean(total),

(np.float64(13600.0),)

In [ ]:
product[np.argmax(total)],

('laptop',)

In [ ]:
product[np.argmin(total)],

('mouse',)

In [ ]:
np.mean(price),

(np.float64(12100.0),)

In [ ]:
np.sum(quantities),

(np.int64(7),)

In [ ]:
np.unique(product, return_counts=True)[0][np.argmax(np.unique(product, return_counts=True)[1])]

'Headphones'

In [ ]:
len(np.unique(product))

5

In [ ]:
len(np.unique(customer_id))
customer_id

array([1001, 1002, 1003, 1004, 1005], dtype=object)

In [ ]:
product.tolist(),


(['laptop', 'mouse', 'keybord', 'monitor', 'Headphones'],)

In [ ]:
# (prod:np.sum(totals[product == prod])) for prod in np.unique(product)

In [ ]:
{prod}

In [ ]:
np.max(price)

np.int64(50000)

In [ ]:
np.min(price),

(np.int64(500),)

In [ ]:
product[quantities>1].tolist(),

(['mouse', 'monitor'],)

In [ ]:
customer_id[quantities>1].tolist(),

([1002, 1004],)

In [ ]:
np.sum(total[customer_id == 1002])

np.int64(1000)

In [ ]:
product[price > 1000].tolist()

['laptop', 'monitor', 'Headphones']

In [ ]:
product[total > 2000].tolist()

['laptop', 'monitor']