In [56]:

import pandas as pd
import numpy as np

In [57]:
list(),str(),tuple(),set(),dict()


([], '', (), set(), {})

In [58]:
x=[1,2,3,4,5,6,7,'Naruto']
x


[1, 2, 3, 4, 5, 6, 7, 'Naruto']

In [59]:
type(x[0]),type(x[1]),type(x[2]),type(x[3]), type(x[4]), type(x[5]), type(x[6]), type(x[7])


(int, int, int, int, int, int, int, str)

In [60]:
y=np.array([3,4,5])
y


array([3, 4, 5])

In [61]:
x=[3,4,5]



In [62]:
x=[3,4,5]



In [63]:
array=([0.6, 0.8, 1. ])

In [64]:
y=np.array([2,3,4,8.6,"data science"])


In [65]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])


(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [66]:
y=np.array(['2', '3', '4', '8.6', 'data science'], dtype='<U32')


In [67]:
for i in range(1,10):
  print(np.random.randint(0,30))

11
12
24
26
22
18
0
17
16


In [68]:
np.random.randint(0,10,(6,6))


array([[3, 5, 9, 8, 2, 1],
       [3, 6, 5, 9, 4, 3],
       [7, 4, 8, 4, 6, 4],
       [4, 1, 0, 6, 3, 6],
       [0, 6, 1, 7, 6, 0],
       [1, 5, 9, 1, 1, 5]])

In [69]:
data=np.random.randint(0,200,(5,5))
data

array([[138, 127, 152, 138,  20],
       [126,  13, 172, 160,  71],
       [ 17, 159,  80, 143,   8],
       [118, 182, 131,  25, 119],
       [138, 137, 113,  94,  13]])

In [70]:
data[0:3,4:5]


array([[20],
       [71],
       [ 8]])

In [71]:
data[0:2,3:5]


array([[138,  20],
       [160,  71]])

In [72]:
data[1:3,4:5]


array([[71],
       [ 8]])

In [73]:
data[-5:-4,-5:-4]


array([[138]])

In [74]:
data.shape


(5, 5)

In [75]:
data.size


25

In [76]:
data.T


array([[138, 126,  17, 118, 138],
       [127,  13, 159, 182, 137],
       [152, 172,  80, 131, 113],
       [138, 160, 143,  25,  94],
       [ 20,  71,   8, 119,  13]])

In [77]:
data**2


array([[19044, 16129, 23104, 19044,   400],
       [15876,   169, 29584, 25600,  5041],
       [  289, 25281,  6400, 20449,    64],
       [13924, 33124, 17161,   625, 14161],
       [19044, 18769, 12769,  8836,   169]])

In [78]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))


In [79]:
x

array([[5, 9, 3],
       [4, 2, 2],
       [6, 3, 0]])

In [80]:
y

array([[6, 4, 3],
       [8, 3, 3],
       [1, 5, 0]])

In [81]:
np.add(x,2)

array([[ 7, 11,  5],
       [ 6,  4,  4],
       [ 8,  5,  2]])

In [82]:
np.multiply(x,2)


array([[10, 18,  6],
       [ 8,  4,  4],
       [12,  6,  0]])

In [83]:
np.divide(x,2)


array([[2.5, 4.5, 1.5],
       [2. , 1. , 1. ],
       [3. , 1.5, 0. ]])

In [84]:
np.floor_divide(x,3)


array([[1, 3, 1],
       [1, 0, 0],
       [2, 1, 0]])

In [85]:
np.floor_divide(x,3)


array([[1, 3, 1],
       [1, 0, 0],
       [2, 1, 0]])

In [86]:
np.exp(x)


array([[1.48413159e+02, 8.10308393e+03, 2.00855369e+01],
       [5.45981500e+01, 7.38905610e+00, 7.38905610e+00],
       [4.03428793e+02, 2.00855369e+01, 1.00000000e+00]])

In [87]:
np.log(x)


/tmp/ipython-input-87-3836458520.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([[1.60943791, 2.19722458, 1.09861229],
       [1.38629436, 0.69314718, 0.69314718],
       [1.79175947, 1.09861229,       -inf]])

In [88]:
np.pow(x,4)


array([[ 625, 6561,   81],
       [ 256,   16,   16],
       [1296,   81,    0]])

In [89]:
np.pow(x,7)


array([[  78125, 4782969,    2187],
       [  16384,     128,     128],
       [ 279936,    2187,       0]])

In [90]:
np.random.rand(5,5)


array([[0.28307305, 0.01459108, 0.04557266, 0.06453912, 0.61291079],
       [0.38502991, 0.79721801, 0.90112407, 0.63084456, 0.29190664],
       [0.28072455, 0.93767191, 0.74937479, 0.70042273, 0.71223207],
       [0.90492959, 0.35982908, 0.30331848, 0.03805191, 0.68111964],
       [0.2368279 , 0.20216126, 0.43995578, 0.03318656, 0.76015436]])

In [91]:
np.random.randn(1600,1300).std()


np.float64(0.9993106531868988)

In [92]:
np.zeros(19)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [93]:
np.zeros((9,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [94]:
np.ones(9)


array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [95]:
np.ones((8,6))


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [96]:
data=np.random.randint(0,40,(20,10))


In [97]:
data

array([[ 2,  8,  3, 16,  0, 16, 13, 39, 12, 13],
       [ 3, 27, 16, 35, 37, 39, 12,  8, 27, 16],
       [26, 12, 26, 37, 13, 39,  7,  0, 32, 15],
       [22, 25, 28, 26,  3, 27, 24, 39, 17, 12],
       [ 8, 26, 13, 33, 15, 18, 38, 16, 35, 19],
       [31, 27, 19,  3, 31, 10,  5,  7,  7, 12],
       [14,  4,  3, 34, 21,  2,  0, 29, 36, 24],
       [38, 27, 24, 25, 36, 35, 39,  2, 24, 12],
       [31, 23, 16, 34, 39, 36, 20, 21,  9,  9],
       [26, 14, 36, 13, 25, 10, 15, 17, 30, 20],
       [11, 23, 16, 34, 12, 38, 10, 20, 37, 31],
       [19, 18,  6, 34,  0, 18,  6, 34,  0, 38],
       [32, 26, 33, 22, 12,  0,  8, 30, 11, 24],
       [ 7, 11, 31, 36, 37, 18, 30, 13,  9, 10],
       [ 7, 23, 19,  4,  0, 20, 34,  7, 23, 34],
       [22, 36, 25, 13, 24, 32,  9, 27,  6, 19],
       [37,  9, 20, 33,  3, 17,  8, 11,  4,  0],
       [ 3, 26, 34,  3,  3, 34, 12,  7,  0, 13],
       [20,  3, 29,  2, 22, 38, 11,  3, 32, 12],
       [28, 10, 10, 30, 19,  2,  3, 25,  3, 35]])

In [98]:
print(data.sum())
print(data.min())
print(data.max())

3821
0
39


In [99]:
data.argmax()


np.int64(7)

In [100]:
data=np.random.randint(0,10,(9,6))
data

array([[8, 4, 5, 3, 4, 6],
       [7, 9, 8, 2, 5, 7],
       [6, 5, 9, 6, 0, 5],
       [5, 2, 7, 0, 1, 7],
       [3, 8, 3, 1, 3, 8],
       [3, 3, 3, 7, 2, 8],
       [0, 2, 6, 1, 2, 4],
       [8, 9, 0, 3, 0, 6],
       [5, 4, 9, 9, 7, 0]])

In [101]:
data.sum(axis=1)


array([30, 38, 31, 22, 26, 26, 15, 26, 34])

In [102]:
data.argmin(axis=1)


array([3, 3, 4, 3, 3, 4, 0, 2, 5])

In [103]:
data.max(axis=0)


array([8, 9, 9, 9, 7, 8])